### ISSUE TITLE
Incompatible with Windows display scaling

### ISSUE THREAD

**Issue by saftle** [Onurtag/TSolidBackground#1]
I absolutely love this AHK script. However, sadly it does not work well with Windows scaling. The top and left side of the window get cut off.

Is there a workaround possible? Thanks!

**Comment by Onurtag** [comment]
I tried but couldn't replicate the bug. 
For now you'll have to use the custom width/height options until I can find a way to fix it.

**Comment by saftle** [comment]
Thanks for taking a look at it! The easiest way to reproduce it, is to change the scaling in Windows (testing with 10 btw) from 100% to 125%. This must be done when the AHK script is not running. I am also testing with Final Fantasy 6 from the Steam store.

Afterwards running the script should show this issue.

I noticed that if the script is already running before scaling, that it works as expected still.

**Comment by Onurtag** [comment]
I think I got it. (By disabling the scaling of those TSB windows)
Check out the new version and let me know if there are any problems.
Thanks for the report.

**Comment by saftle** [comment]
It works perfect. Thank you very much!
